services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: until-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: until-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  # Для запуска приложения используем команды:
  # docker exec -it java-app run-parser
  # docker exec -it java-app run-mongo-loader
  # docker exec -it java-app run-elastic-loader
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    depends_on:
      - mongodb
      - elasticsearch
